name: ci

on:
    push:
        branches: [main]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out git
              uses: actions/checkout@v4
            - name: Build Image
              run: docker compose build
